load('data_16');

% L, кДж/кг
L = c_1.*((m_1+m_c)./m_2.*(theta-theta_1) - (100-theta)).*1e-3;
d_L = c_1./m_2.*sqrt( ...
    ((theta-theta_1).*d_m).^2 + ...
    ((m_1+m_c)./m_2.*(theta-theta_1).*d_m).^2 + ...
    ((m_1+m_c).*d_theta).^2 + ...
    ((m_1+m_c+m_2).*d_theta).^2 ...
    ).*1e-3;
% λ, кДж/кг
lambda = (c_1.*(M_1+m_c)./M_2.*(THETA_1-THETA) - c_1.*THETA + c_2.*THETA_2).*1e-3;
d_lambda = c_1./M_2.*sqrt( ...
    ((THETA_1-THETA).*d_m).^2 + ...
    ((M_1+m_c)./M_2.*(THETA_1-THETA).*d_m).^2 + ...
    ((M_1+m_c).*d_theta).^2 + ...
    (M_2.*c_2./c_1.*d_THETA_2).^2 + ...
    ((M_1+m_c+M_2).*d_theta).^2 ...
    ).*1e-3;
%% Вывод результатов
printresult(L,d_L,'pm','L','кДж/кг');
printresult(lambda,d_lambda,'pm','λ','кДж/кг');